# SpiritFoxOS Build System
# Supports: BIOS (Multiboot2) and UEFI boot modes
#
# Requires:
#   BIOS mode: nasm, gcc, ld, grub-mkrescue, xorriso, mtools
#   UEFI mode: nasm, gcc, ld, python3, grub-mkrescue, OVMF firmware
#
# Usage:
#   make            - Build kernel (UEFI mode by default)
#   make bios       - Build in legacy BIOS/Multiboot2 mode
#   make run        - Run in QEMU with UEFI (OVMF)
#   make run-bios   - Run in QEMU with legacy BIOS
#   make iso        - Create UEFI-bootable ISO
#   make iso-bios   - Create BIOS-bootable ISO (GRUB)

# ============================================================
# Toolchain Configuration
# ============================================================
CC      = gcc
LD      = ld
NASM    = nasm

# Try to detect cross-compiler
CROSS_CC = x86_64-elf-gcc
CROSS_LD = x86_64-elf-ld

ifneq ($(shell which $(CROSS_CC) 2>/dev/null),)
CC  = $(CROSS_CC)
LD  = $(CROSS_LD)
endif

# ============================================================
# Directories
# ============================================================
SRCDIR  = src
BUILDDIR = build
ISODIR  = iso

# ============================================================
# Source Files
# ============================================================
C_SRCS   = $(wildcard $(SRCDIR)/kernel/*.c)

BIOS_ASM_SRCS  = $(SRCDIR)/boot/boot.asm
KERNEL_ASM_SRCS = $(wildcard $(SRCDIR)/kernel/*.asm)

# ============================================================
# Compiler Flags (Common)
# ============================================================
COMMON_CFLAGS = -ffreestanding -fno-stack-protector \
                -mno-mmx -mno-sse -mno-sse2 -mno-sse3 \
                -m64 -Wall -Wextra -Werror \
                -I$(SRCDIR)/include -I$(SRCDIR)/kernel \
                -nostdlib -nostdinc -fno-builtin -nodefaultlibs

BIOS_CFLAGS = $(COMMON_CFLAGS) -fno-pie -fno-pic -mcmodel=small

# UEFI flags: use default code model (RIP-relative) for relocatable code
# Base relocations are generated by elf2pe.py from ELF relocation entries
UEFI_CFLAGS = $(COMMON_CFLAGS) -fpic -mno-red-zone \
              -DBOOT_MODE_UEFI

# ============================================================
# Linker Flags
# ============================================================
BIOS_LDFLAGS = -T linker.ld -nostdlib -static
UEFI_LDFLAGS = -T linker_efi.ld -nostdlib -static

# ============================================================
# Targets
# ============================================================
BIOS_TARGET = $(BUILDDIR)/kernel.elf
UEFI_ELF    = $(BUILDDIR)/kernel_efi.elf
UEFI_TARGET = $(BUILDDIR)/BOOTX64.EFI

# ============================================================
# Object Files
# ============================================================
C_OBJS      = $(patsubst $(SRCDIR)/%.c,$(BUILDDIR)/%.o,$(C_SRCS))
BIOS_ASM_OBJS = $(patsubst $(SRCDIR)/%.asm,$(BUILDDIR)/%.o,$(BIOS_ASM_SRCS)) \
                $(patsubst $(SRCDIR)/%.asm,$(BUILDDIR)/%.o,$(KERNEL_ASM_SRCS))
UEFI_ASM_OBJS = $(patsubst $(SRCDIR)/%.asm,$(BUILDDIR)/%.o,$(KERNEL_ASM_SRCS))

BIOS_OBJS = $(BIOS_ASM_OBJS) $(C_OBJS)
UEFI_OBJS = $(BUILDDIR)/boot/efi_boot.o $(C_OBJS) $(UEFI_ASM_OBJS)

# ============================================================
# Build Rules
# ============================================================

.PHONY: all bios uefi clean iso iso-bios run run-bios debug debug-uefi

all: uefi

# ---- BIOS Build ----
bios: $(BIOS_TARGET)
	@echo "=== SpiritFoxOS BIOS build complete ==="

$(BIOS_TARGET): $(BIOS_OBJS)
	@mkdir -p $(BUILDDIR)
	$(LD) $(BIOS_LDFLAGS) -o $@ $(BIOS_OBJS)
	@echo "Built BIOS kernel: $@"

# ---- UEFI Build (ELF → PE via elf2pe.py) ----
uefi: $(UEFI_TARGET)
	@echo "=== SpiritFoxOS UEFI build complete ==="

$(UEFI_ELF): $(UEFI_OBJS)
	@mkdir -p $(BUILDDIR)
	$(LD) $(UEFI_LDFLAGS) -o $@ $(UEFI_OBJS)
	@echo "Built UEFI ELF intermediate: $@"

$(UEFI_TARGET): $(UEFI_ELF)
	python3 scripts/elf2pe.py $< $@
	@echo "Built UEFI executable: $@"

# ---- Compile C sources ----
$(BUILDDIR)/kernel/%.o: $(SRCDIR)/kernel/%.c
	@mkdir -p $(dir $@)
	$(CC) $(UEFI_CFLAGS) -c -o $@ $<

$(BUILDDIR)/boot/efi_boot.o: $(SRCDIR)/boot/efi_boot.c
	@mkdir -p $(dir $@)
	$(CC) $(UEFI_CFLAGS) -mabi=ms -c -o $@ $<

$(BUILDDIR)/kernel/isr.o: $(SRCDIR)/kernel/isr.asm
	@mkdir -p $(dir $@)
	$(NASM) -f elf64 -o $@ $<

# ============================================================
# ISO Creation
# ============================================================

iso: $(UEFI_TARGET)
	@mkdir -p $(ISODIR)/EFI/BOOT
	@mkdir -p $(ISODIR)/boot/grub
	cp $(UEFI_TARGET) $(ISODIR)/EFI/BOOT/BOOTX64.EFI
	cp $(UEFI_TARGET) $(ISODIR)/boot/kernel.efi
	grub-mkrescue -o $(BUILDDIR)/spiritfoxos.iso $(ISODIR) \
		-- -efi-boot-part --efi-boot-image || \
		echo "Note: grub-mkrescue may require xorriso and mtools packages"
	@echo "Created UEFI ISO: $(BUILDDIR)/spiritfoxos.iso"

iso-bios: $(BIOS_TARGET)
	@mkdir -p $(ISODIR)/boot/grub
	cp $(BIOS_TARGET) $(ISODIR)/boot/kernel.elf
	grub-mkrescue -o $(BUILDDIR)/spiritfoxos_bios.iso $(ISODIR) 2>/dev/null || \
		echo "Note: grub-mkrescue may require xorriso and mtools packages"
	@echo "Created BIOS ISO: $(BUILDDIR)/spiritfoxos_bios.iso"

# ============================================================
# QEMU Run Targets
# ============================================================

OVMF_CODE ?= /usr/share/OVMF/OVMF_CODE.fd
OVMF_VARS ?= /usr/share/OVMF/OVMF_VARS.fd

ifeq ($(wildcard $(OVMF_CODE)),)
OVMF_CODE = /usr/share/edk2/ovmf/OVMF_CODE.fd
endif
ifeq ($(wildcard $(OVMF_CODE)),)
OVMF_CODE = /usr/share/qemu/OVMF_CODE.fd
endif

run: $(UEFI_TARGET)
	@if [ ! -f "$(OVMF_CODE)" ]; then \
		echo "Error: OVMF firmware not found at $(OVMF_CODE)"; \
		exit 1; \
	fi
	qemu-system-x86_64 \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS) \
		-drive format=raw,file=fat:rw:$(ISODIR) \
		-m 128M -net none

run-iso: iso
	@if [ ! -f "$(OVMF_CODE)" ]; then echo "Error: OVMF firmware not found"; exit 1; fi
	qemu-system-x86_64 \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS) \
		-cdrom $(BUILDDIR)/spiritfoxos.iso \
		-m 128M -net none

run-bios: iso-bios
	qemu-system-x86_64 -cdrom $(BUILDDIR)/spiritfoxos_bios.iso -m 128M

debug-uefi: $(UEFI_TARGET)
	@if [ ! -f "$(OVMF_CODE)" ]; then echo "Error: OVMF firmware not found"; exit 1; fi
	qemu-system-x86_64 \
		-drive if=pflash,format=raw,readonly=on,file=$(OVMF_CODE) \
		-drive if=pflash,format=raw,file=$(OVMF_VARS) \
		-drive format=raw,file=fat:rw:$(ISODIR) \
		-m 128M -serial stdio -d int,cpu_reset -net none

debug: iso-bios
	qemu-system-x86_64 -cdrom $(BUILDDIR)/spiritfoxos_bios.iso -m 128M -serial stdio -d int,cpu_reset

# ============================================================
# Clean
# ============================================================
clean:
	rm -rf $(BUILDDIR) $(ISODIR)/boot/kernel.elf $(ISODIR)/boot/kernel.efi
	rm -rf $(ISODIR)/EFI
