#!/usr/bin/env python3
"""
png2c.py - Convert PNG image to a C header with raw XRGB8888 pixel data.

Usage: python3 tools/png2c.py <input.png> <output.h> [<max_size>]

The image is resized to fit within max_size x max_size while keeping
aspect ratio, then stored as a static const uint32_t array in XRGB8888
format (0x00RRGGBB). Transparent pixels are alpha-blended onto a black
background.
"""

import sys
from PIL import Image


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <input.png> <output.h> [<max_size>]", file=sys.stderr)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]
    max_size = int(sys.argv[3]) if len(sys.argv) > 3 else 300

    img = Image.open(input_path)

    # Convert to RGBA for consistent alpha handling
    if img.mode != "RGBA":
        img = img.convert("RGBA")

    # Resize to fit within max_size while preserving aspect ratio
    w, h = img.size
    scale = min(max_size / w, max_size / h)
    if scale < 1.0:
        new_w = int(w * scale)
        new_h = int(h * scale)
        img = img.resize((new_w, new_h), Image.LANCZOS)
    else:
        new_w, new_h = w, h

    # Alpha-blend onto black background and convert to RGB
    bg = Image.new("RGBA", img.size, (0, 0, 0, 255))
    bg.paste(img, mask=img.split()[3])  # use alpha channel as mask
    img = bg.convert("RGB")

    pixels = img.load()
    w, h = img.size

    # Write C header
    with open(output_path, "w") as f:
        f.write("/* Auto-generated by tools/png2c.py - DO NOT EDIT */\n")
        f.write("#ifndef LOGO_DATA_H\n")
        f.write("#define LOGO_DATA_H\n\n")
        f.write(f"#define LOGO_WIDTH  {w}\n")
        f.write(f"#define LOGO_HEIGHT {h}\n\n")
        f.write("static const uint32_t logo_pixels[] = {\n")

        for y in range(h):
            row_vals = []
            for x in range(w):
                r, g, b = pixels[x, y]
                pixel = (r << 16) | (g << 8) | b  # XRGB8888
                row_vals.append(f"0x{pixel:06X}")
            f.write("    " + ", ".join(row_vals) + ",\n")

        f.write("};\n\n")
        f.write("#endif /* LOGO_DATA_H */\n")

    print(f"Generated {output_path}: {w}x{h} = {w * h} pixels ({w * h * 4} bytes)")


if __name__ == "__main__":
    main()
